services:
  opengr8on:
    image: ghcr.io/psobiech/opengr8on:edge
    command: wlan0
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    build:
      target: app-runtime
    network_mode: "host"
    volumes:
      - type: bind
        source: ./runtime
        target: /opt/docker/runtime
      - type: tmpfs
        target: /tmp
