services:
  opengr8on:
    image: ghcr.io/psobiech/opengr8on:raw
    command: wlan0
    restart: unless-stopped
    read_only: false
    privileged: true
    cap_add:
      - NET_BIND_SERVICE
      - NET_BROADCAST
      - SETPCAP
    build:
      target: app-runtime
    network_mode: "host"
    volumes:
      - type: bind
        source: ./runtime
        target: /opt/docker/runtime
      - type: tmpfs
        target: /tmp
