name: Package Cleanup

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'pl.psobiech.opengr8on.parent'
          package-type: 'maven'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'pl.psobiech.opengr8on.tftp'
          package-type: 'maven'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'pl.psobiech.opengr8on.common'
          package-type: 'maven'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'pl.psobiech.opengr8on.client'
          package-type: 'maven'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'pl.psobiech.opengr8on.lib'
          package-type: 'maven'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'pl.psobiech.opengr8on.vclu'
          package-type: 'maven'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          owner: 'psobiech'
          package-name: 'opengr8on'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
