name: semgrep

on:
  push:
    branches: [ "develop" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]

jobs:
  semgrep-full:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scan
        run: |
          semgrep \
            --verbose \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default" \
            --config="p/owasp-top-ten" \
            --config="p/cwe-top-25" \
            --config="p/secrets"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: report.sarif
          category: semgrep
